git add render.yaml
git commit -m "# Exported from Render 
services:
- type: web
  name: ELITE-PRO-V2
  runtime: docker
  repo: https://github.com/Impec-cable/ELITE-PRO-V2
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
"
git push
